### ISSUE TITLE
320kbps and 48khz selected but it converted to 128kbps and 44khz

### ISSUE THREAD

**Issue by ikillcypher2** [R3DST0RM/MediaDownloader2#6]
http://downloader.r3d-soft.de/

hello 

I have tried to use your tool to download a soundcloud song but it seems like the settings was not registered and it downloaded and converted it to 128kbps with 44khz.

**Comment by R3DST0RM** [comment]
Hello ikillcypher2,
thanks for your report on that issue.

Indeed, the settings weren't "registered" at all. I fixed this issue, so soundcloud should now work as expected for converting files.

**Comment by R3DST0RM** [comment]
Can you verify, that this isse has been solved for you?

**Comment by ikillcypher2** [comment]
Fixed :)

anyway will there be a desktop version? where something I can download and place on my desktop ? would love to have it

**Comment by R3DST0RM** [comment]
Well, if you are looking for a desktop version of "http://downloader.r3d-soft.de", the goal of this repository is to build a cross-platform desktop application to use this service.
Otherwise there is a predecessor of this repository where we have a fully functional desktop application.
Which you can find here:
http://downloader.r3d-soft.de
and here:
http://github.com/MediaDownloader/ 
But since this project has been abandoned it is possible, that a few downloaders there won't work anymore.

**Comment by ikillcypher2** [comment]
hi  R3DST0RM 

what I meant is a JavaFX Version a executable jar file that will run from desktop without the need to go to the internet.

**Comment by R3DST0RM** [comment]
Hi,
I see, yes this is what I am trying to create here. 
Since my old project used Java.Swing I decided to port this one to JavaFX using the new API we provide.

This means, our repository here is _still work in progress_ and **as soon as possible** there will be a **JavaFX executable**.

But nonetheless you are able to build your "alpha" executable from this source, if needed.
Make sure you have Java8 (from oracle) installed and then you are good to go.

If you need any help or have further questions, just send me an email: r3dst0rm@r3d-soft.de
